### ISSUE TITLE
How can you do a non reactive query? 

### ISSUE THREAD

**Issue by ghost** [numtel/pg-live-select#6]
Also can you run use PostgreSQL for primarily non reactive and use MongoDB for reactive since it has Minimongo. Is it possible to run both?

**Comment by numtel** [comment]
The [`node-postgres` package](https://github.com/brianc/node-postgres) is included in the `numtel:pg` Meteor package. See the[ leaderboard example for using it to perform a single query non-reactively in a Meteor method](https://github.com/numtel/meteor-pg-leaderboard/blob/master/leaderboard.js#L111-126).

**Comment by ghost** [comment]
thanks and does mongodb still work when using it?
